#!/usr/bin/env python3
"""Fetch self-hosted WOFF2 fonts for the Haris legal sites (build-time only).

Downloads Inter (Latin) and Cairo (Arabic + Latin) at weights 400/600/700 from
the Google Fonts CSS API and writes them with stable filenames into each site's
fonts/ folder, plus a fonts.css @font-face snippet. Runtime pages make NO
external request (FR-015) — this script only runs during development.

Usage:  python tools/legal-sites/fetch-fonts.py
"""
import os
import re
import sys
import urllib.request

UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120 Safari/537.36")
CSS_URL = ("https://fonts.googleapis.com/css2?"
           "family=Inter:wght@400;600;700&family=Cairo:wght@400;600;700&display=swap")

# Which (family, subset) pairs we keep, and the output name prefix.
WANT = {
    ("Inter", "latin"): "inter",
    ("Cairo", "arabic"): "cairo-ar",
    ("Cairo", "latin"): "cairo-latin",
}

ROOT = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(ROOT, "..", ".."))
SITES = [os.path.join(REPO, "app", "src", "main", "assets", "websites", s, "fonts")
         for s in ("privacy-policy", "terms")]


def get(url, binary=False):
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as r:
        return r.read() if binary else r.read().decode("utf-8")


def parse_css(css):
    """Yield (family, subset, weight, url). Subset comes from the /* comment */."""
    blocks = re.split(r"/\*\s*([\w-]+)\s*\*/", css)
    # blocks = ['', subset1, face1, subset2, face2, ...]
    for i in range(1, len(blocks) - 1, 2):
        subset = blocks[i]
        face = blocks[i + 1]
        fam = re.search(r"font-family:\s*'([^']+)'", face)
        wght = re.search(r"font-weight:\s*(\d+)", face)
        url = re.search(r"url\((https://[^)]+\.woff2)\)", face)
        if fam and wght and url:
            yield fam.group(1), subset, wght.group(1), url.group(1)


def main():
    css = get(CSS_URL)
    faces = []  # (outname, weight, family_css, unicode_hint)
    seen = set()
    for fam, subset, wght, url in parse_css(css):
        key = (fam, subset)
        if key not in WANT:
            continue
        prefix = WANT[key]
        name = f"{prefix}-{wght}.woff2"
        if name in seen:
            continue
        seen.add(name)
        data = get(url, binary=True)
        for site in SITES:
            os.makedirs(site, exist_ok=True)
            with open(os.path.join(site, name), "wb") as f:
                f.write(data)
        faces.append((name, wght, "Inter" if fam == "Inter" else "Cairo", prefix))
        print(f"  {name:22} {len(data):>7} bytes  ({fam} {subset} {wght})")

    # Emit a fonts.css snippet (informational; the real @font-face lives in styles.css)
    lines = ["/* Generated by fetch-fonts.py — self-hosted, no external requests */"]
    for name, wght, family, prefix in faces:
        lines.append(
            f"@font-face{{font-family:'{family}';font-style:normal;"
            f"font-weight:{wght};font-display:swap;src:url('fonts/{name}') format('woff2');}}")
    snippet = "\n".join(lines) + "\n"
    for site in SITES:
        with open(os.path.join(os.path.dirname(site), "fonts.css.txt"), "w",
                  encoding="utf-8") as f:
            f.write(snippet)
    print(f"Done. {len(faces)} font files x {len(SITES)} sites.")


if __name__ == "__main__":
    try:
        main()
    except Exception as e:  # noqa
        print(f"ERROR: {e}", file=sys.stderr)
        sys.exit(1)
